const actionTypes = {
  LOADING_PAGE: "SET/LOADING_PAGE",
  LOAD_API_DATA: "SET/LOAD_API_DATA",
  FILTER_DROPDOWN: "SET/FILTER_DROPDOWN",
  FILTERED_API_DATA: "SET/FILTERED_API_DATA",
};

export default actionTypes;
